name: 'ssh'
description: ''
author: ''
inputs:
  ssh-private-key:
    description: "ssh private key"
    required: true
  source:
    description: "source"
    required: true
  host:
    description: "host"
    required: true
  target:
    description: "target"
    required: true
    default: "~"
branding:
  icon: 'box'
  color: 'green'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.ssh-private-key }}
    - ${{ inputs.source }}
    - ${{ inputs.host }}
    - ${{ inputs.target }}